StartupEvents.registry("fluid", event => {
    event.create("kubejs:ketchup", "thick")
        .tint(0xFF0000)
        .noBucket()
        .noBlock()
    event.create("kubejs:burger_relish", "thick")
        .tint(0xAA5500)
        .noBucket()
        .noBlock()
    event.create("kubejs:mayonnaise", "thick")
        .tint(0xFFFFEE)
        .noBucket()
        .noBlock()
    event.create("kubejs:mustard", "thick")
        .tint(0xFFFF00)
        .noBucket()
        .noBlock()
})